//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.30 at 10:33:19 PM CEST 
//


package com.tradeengineproject.profilereader.ws_bindings.operations;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tradeengineproject.profilereader.ws_bindings.operations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tradeengineproject.profilereader.ws_bindings.operations
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateLoyalityAccountRequest }
     * 
     */
    public CreateLoyalityAccountRequest createCreateLoyalityAccountRequest() {
        return new CreateLoyalityAccountRequest();
    }

    /**
     * Create an instance of {@link DeleteLoyalityAccountResponse }
     * 
     */
    public DeleteLoyalityAccountResponse createDeleteLoyalityAccountResponse() {
        return new DeleteLoyalityAccountResponse();
    }

    /**
     * Create an instance of {@link GetLoyalityAccountResponse }
     * 
     */
    public GetLoyalityAccountResponse createGetLoyalityAccountResponse() {
        return new GetLoyalityAccountResponse();
    }

    /**
     * Create an instance of {@link GetLoyalityAccountRequest }
     * 
     */
    public GetLoyalityAccountRequest createGetLoyalityAccountRequest() {
        return new GetLoyalityAccountRequest();
    }

    /**
     * Create an instance of {@link DeleteLoyalityAccountRequest }
     * 
     */
    public DeleteLoyalityAccountRequest createDeleteLoyalityAccountRequest() {
        return new DeleteLoyalityAccountRequest();
    }

    /**
     * Create an instance of {@link CreateLoyalityAccountResponse }
     * 
     */
    public CreateLoyalityAccountResponse createCreateLoyalityAccountResponse() {
        return new CreateLoyalityAccountResponse();
    }

}
