//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.30 at 10:33:19 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://operations.ws_bindings.tradeengine.tradeengineproject.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tradeengineproject.tradeengine.ws_bindings.operations;
